apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v11
  template:
    metadata:
      labels:
        app: emoji-svc
        version: v11
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      nodeSelector:
        role: workload
      serviceAccountName: emoji
      containers:
      - env:
        - name: GRPC_PORT
          value: "8081"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8081
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: v11
  template:
    metadata:
      labels:
        app: voting-svc
        version: v11
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      nodeSelector:
        role: workload
      serviceAccountName: voting
      containers:
      - env:
        - name: GRPC_PORT
          value: "8082"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
        name: voting-svc
        ports:
        - containerPort: 8082
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      labels:
        app: web-svc
        version: v11
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "emoji-svc:8081,voting-svc:8082"
    spec:
      nodeSelector:
        role: workload
      serviceAccountName: web
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: localhost:8081
        - name: VOTINGSVC_HOST
          value: localhost:8082
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
