apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: emoji-svc
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
  - name: prom
    port: 8801
    targetPort: 8801
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: voting-svc
  ports:
  - name: grpc
    port: 8082
    targetPort: 8082
  - name: prom
    port: 8801
    targetPort: 8801
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080
