kind: ServiceAccount
apiVersion: v1
metadata:
  name: emoji
  namespace: {{.Release.Namespace}}
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: emoji-svc-{{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
spec:
  protocol: "grpc"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: voting
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-svc
  namespace: {{.Release.Namespace}}
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: voting-svc-{{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
spec:
  protocol: "grpc"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-svc
  namespace: {{.Release.Namespace}}
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web-svc-{{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
spec:
  protocol: "http"
